import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import '@mantine/core/styles.css';
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from '@mantine/core';
import './globals.css';
import Footer from './_components/footer';

export const metadata: Metadata = {
  title: 'The Tech | Photos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ThemeProvider>
          <MantineProvider>
            {children}
            <Footer />
          </MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
